#!/bin/env bash


##### FUNCTIONS #####

get_apps_infos(){
  # getting current desktop
  cur_desktop=$(wmctrl -d | grep '*' | cut -d ' ' -f1)

  # getting appd IDs in current desktop
  apps_ids=($(wmctrl -l | grep " ${cur_desktop} " | tr -s ' ' | cut -d ' ' -f 1))
}


focus_up(){
  # getting current app y_offset
  cur_y_offset=($(wmctrl -lG | grep $(xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/') | tr -s ' ' | cut -d ' ' -f 4))
  
  # getting the next window at left
  for id in ${apps_ids[@]}; do
    _y=($(wmctrl -lG | grep $id | tr -s ' ' | cut -d ' ' -f 4)) 
  
    if [ $_y -lt $cur_y_offset ]; then
      cmd="wmctrl -i -a \"$id\""
      eval $cmd
      break
    fi
  done
}

focus_down(){
  # getting current app x_offset
  cur_y_offset=($(wmctrl -lG | grep $(xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/') | tr -s ' ' | cut -d ' ' -f 4))
  
  # getting the next window at left
  for id in ${apps_ids[@]}; do
    _y=($(wmctrl -lG | grep $id | tr -s ' ' | cut -d ' ' -f 4)) 
  
    if [ $_y -gt $cur_y_offset ]; then
      cmd="wmctrl -i -a \"$id\""
      eval $cmd
      break
    fi
  done
}

focus_left(){
  # getting current app x_offset
  cur_x_offset=($(wmctrl -lG | grep $(xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/') | tr -s ' ' | cut -d ' ' -f 3))
  
  # getting the next window at left
  for id in ${apps_ids[@]}; do
    _x=($(wmctrl -lG | grep $id | tr -s ' ' | cut -d ' ' -f 3)) 
  
    if [ $_x -lt $cur_x_offset ]; then
      x_offset=${_x}
      cmd="wmctrl -i -a \"$id\""
      eval $cmd
      break
    fi
  done
}

focus_right(){
  # getting current app x_offset
  cur_x_offset=($(wmctrl -lG | grep $(xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/') | tr -s ' ' | cut -d ' ' -f 3))
  
  # getting the next window at left
  for id in ${apps_ids[@]}; do
    _x=($(wmctrl -lG | grep $id | tr -s ' ' | cut -d ' ' -f 3)) 
  
    if [ $_x -gt $cur_x_offset ]; then
      cmd="wmctrl -i -a \"$id\""
      eval $cmd
      break
    fi
  done
}


###### MAIN ######
case $1 in
-up)
    get_apps_infos
    focus_up
    ;;
-down)
    get_apps_infos
    focus_down
    ;;
-left)
    get_apps_infos
    focus_left
    ;;
-right)
    get_apps_infos
    focus_right
    ;;
-h)
    echo "Usage: focus_window [-up/-down/-left/-right]"
    ;;
*)
    echo "Choose between:\n-up\t-down\t-left\t-right"
    ;;
esac
